from typing import TypedDict

class AppState(TypedDict):
    """
    Represents the state of our application graph.
    This dictionary is passed between all nodes.
    """
    youtube_url: str
    target_language: str
    
    # Paths will be populated by the nodes
    original_video_path: str
    original_audio_path: str
    
    # Data generated by AI
    transcription: str
    
    # To handle potential issues
    error: str | None